# Meta data
title: "LogosArt | Logopedia medialna"
description: "LogosArt oferuje profesjonalne usługi logopedyczne dla dorosłych, dzieci i młodzieży. Specjalizujemy się
              w logopedii medialnej, pomocy osobom, których głos i dykcja stanowią podstawę warsztatu pracy oraz służymy
              radą i doświadczeniem młodzieży w przygotowaniach do egzaminów do szkoły filmowej i teatralnej."
keywords: "logopeda, logopedia, specjalista logopeda, łódź, logopeda łódź, LogosArt, Grażyna Walasek,
            logopedia medialna, logopeda dla dzieci, logopeda dla młodzieży, logopeda dla dorosłych,
            przygotowanie do szkoły teatralnej, przygotowanie do szkoły filmowej,
            poprawa dykcji, poprawa artykulacji, sztuka prezentacji"
url: "http://logosart.pl"
thumbnail: "img/thumbnail.png"
logo: "img/logo.png"
hero: "img/hero.jpg"

# Contact info
contact:
    address: Tramwajowa 21 m.10 <br> 90-132 Łódź <br> Polska

# Map
map:
    address: Tramwajowa 21, Łódź, Poland
    address_details: img/logo.png

# Footer
copyright: © 2017 Michał Siatkowski - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package*.json,
    node_modules,
    .gitignore,
    .idea,
    src,
    test,
    Gemfile*,
    webpack*
]

keep_files: [
  dist
]

plugins:
  - jekyll-sitemap